

apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
          lameduck 5s
        }
        ready
        kubernetes ${ClusterDomain} REVERSE_CIDRS {
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts {
          #此处输入自定义解析域名,格式为: ip 域名 多个域名  例如下:
          #1.1.1.1 huisebug.org huisebug.com
          fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf {
          max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }        