apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kube-apiserver
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - /usr/local/bin/kube-apiserver 
    - --authorization-mode=Node,RBAC 
    - --enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeClaimResize,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,Priority 
    - --advertise-address=${bind} 
    - --bind-address=0.0.0.0  
    - --secure-port=6443 
    - --allow-privileged=true 
    - --audit-log-maxage=30 
    - --audit-log-maxbackup=3 
    - --audit-log-maxsize=100 
    - --audit-log-path=/var/log/audit.log 
    - --storage-backend=etcd3 
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt 
    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt 
    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key 
    - --etcd-servers=${etcd-servers}
    - --event-ttl=1h 
    - --enable-bootstrap-token-auth 
    - --client-ca-file=/etc/kubernetes/pki/ca.crt 
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt 
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key 
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname 
    - --service-cluster-ip-range=${service-cluster-ip-range}
    - --service-node-port-range=30000-32767 
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub 
    - --service-account-issuer=https://kubernetes.default.svc.cluster.local 
    - --service-account-signing-key-file=/etc/kubernetes/pki/sa.key 
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt 
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key 
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt 
    - --requestheader-username-headers=X-Remote-User 
    - --requestheader-group-headers=X-Remote-Group 
    - --requestheader-allowed-names=front-proxy-client 
    - --requestheader-extra-headers-prefix=X-Remote-Extra- 
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt 
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key 
    - --v=2    

    image: ${KubernetesImage}
    imagePullPolicy: IfNotPresent
    name: kube-apiserver
    resources:
      requests:
        cpu: 250m
    securityContext:
      privileged: false
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: conf
 
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes
      type: DirectoryOrCreate
    name: conf
