apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kube-scheduler
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - /usr/local/bin/kube-scheduler 
    - --kubeconfig=/etc/kubernetes/scheduler.kubeconfig
    - --bind-address=0.0.0.0 
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.kubeconfig 
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.kubeconfig 
    - --client-ca-file=/etc/kubernetes/pki/ca.crt 
    - --leader-elect=true 
    - --leader-elect-lease-duration=60s 
    - --leader-elect-renew-deadline=40s 
    - --leader-elect-retry-period=10s 
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt 
    - --v=2  

    image: ${KubernetesImage}
    imagePullPolicy: IfNotPresent
    name: kube-scheduler
    resources:
      requests:
        cpu: 250m
    securityContext:
      privileged: false
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: conf
 
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes
      type: DirectoryOrCreate
    name: conf
